"""Coluna de checkin adicionada

Revision ID: 299e10538d92
Revises: 0412c4d5bb7a
Create Date: 2025-09-19 20:19:09.829481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299e10538d92'
down_revision: Union[str, Sequence[str], None] = '0412c4d5bb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'checked_at')
    # ### end Alembic commands ###
