"""Nova Migration Events Comissioner

Revision ID: 594389e6c747
Revises: 5691bd6dfae8
Create Date: 2025-10-05 13:37:23.350897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594389e6c747'
down_revision: Union[str, Sequence[str], None] = '5691bd6dfae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissioner_events',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.add_column('products', sa.Column('status', sa.String(), nullable=False))
    op.add_column('sales', sa.Column('sale_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'sale_price')
    op.drop_column('products', 'status')
    op.drop_table('commissioner_events')
    # ### end Alembic commands ###
