"""Alteração da Tabela Product

Revision ID: b2794db114c0
Revises: 63318b6777df
Create Date: 2025-09-23 18:02:22.266618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2794db114c0'
down_revision: Union[str, Sequence[str], None] = '63318b6777df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('description', sa.String(), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_products_name_product'), table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.drop_column('products', 'description_product')
    op.drop_column('products', 'stack')
    op.drop_column('products', 'name_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name_product', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('stack', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('description_product', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index(op.f('ix_products_name_product'), 'products', ['name_product'], unique=False)
    op.drop_column('products', 'stock')
    op.drop_column('products', 'description')
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
