"""Add table Event and Fix products

Revision ID: bda2d95048d7
Revises: 97fd2de4dd8d
Create Date: 2025-09-17 17:28:01.370343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda2d95048d7'
down_revision: Union[str, Sequence[str], None] = '97fd2de4dd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'event_id')
    # ### end Alembic commands ###
